config/routes.rb
Rails.application.routes.draw do
  root 'homepage#show'

  get '/results',       to: "results#index"
  get '/resume',        to: "resume#show"
  get '/partners',      to: "partners#index"
  get '/photos',        to: "photos#index"
  get '/bikes',         to: "bikes#index"
  get '/calender',      to: "calender#index"  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/result.rb
class Result < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController

  def index
  end
end

app/controllers/calender_controller.rb
class CalenderController < ApplicationController

  def index
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def show
  end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController

  def index

  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index

  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

  def index
    @results = Result.all
  end
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/index.html.erb
<div class="container">
  <h2>Bikes</h2>
</div>

app/views/calender/index.html.erb
<div class="container">
  <h2>Calender</h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ColinOsborn</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <div class="page-header">
        <div class="well">

          <h1>Colin Osborn <small>Professional Programmer ~ Professional Mountain Bike Racer</small></h1>
          <img src="https://3.bp.blogspot.com/-orG3rXR_2qg/V7qAuaqf8hI/AAAAAAAAFew/H5wU7TzVqT4uuLZJ2ZzbEUlSs9vA_e7vwCLcB/s1600/1522701_10152875686302065_300515172049369132_o.jpg" class="img-responsive header-image center-block">
        </div>
      </div>
    </div>
    <div class="container">
      <div class="col-md-2">
      </div>
      <div class="panel panel-default col-md-8">
        <h4><%= link_to "News", root_path %> - <%= link_to "Results", results_path %> - <%= link_to "Calender", calender_path %> - <%= link_to "Photos", photos_path %> - <%= link_to "Resume", resume_path %> - <%= link_to "Bikes", bikes_path %> - <%= link_to "Partners", partners_path %> - <%= link_to "Contact" %> - <%= link_to "Friends" %></h4>
      </div>
      <div class="col-md-2">
      </div>
    </div>
    <%= yield %>
  </body>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>

app/views/partners/index.html.erb
<div class="container">
  <h2>Partners</h2>
</div>

app/views/photos/index.html.erb
<div class="container">
  <h2>Photos</h2>
</div>

app/views/results/index.html.erb
<div class="container">
  <div class="well well-lg">
    <h2>Results</h2>

    <ul>
      <% @results.each do |result| %>
      <li><%= result.placing %> - <%= result.race %> - <%= result.location %> - <%= result.year %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/resume/show.html.erb
<div class="container">
  <div class="well">

    <h2>Resume</h2>

    <img src="https://1.bp.blogspot.com/-q7qcivY-X9k/V7qEipnPmSI/AAAAAAAAFe8/MbEaHNeYYqsSsgQdmA1LS8LnnhKmPz30QCLcB/s320/1187306_10151898735237065_1314364430_n.jpg" class="img-responsive center-block">
    <div class="centered-header">
      <h2>Colin Osborn</h2>
      <h3>970.618.1212  | Carbondale, CO 81623 | Colin.Osborn@gmail.com</h3>
      <h3><em>Software Development ~ Web Design ~ Branding </em></h3>
    </div>
    <div class="qualifications">
      <h3>QUALIFICATIONS PROFILE</h3>
      <ul>
        <li>Motivated, deadline-focused professional offering exemplary talents in communications, sponsorship programs, tradeshow execution, sales, contract management, and negotiations</li>
        <li>Programming skills with proficiency in Ruby, Ruby on Rails, HTML/CSS, JavaScript, JQuery all with Agile Methodologies</li>
        <li>Highly capable marketing professional with expertise in implementing customer-focused marketing plans, sales initiatives and SEO</li>
        <li>Adept at working within high-pressure environments; proactively foster cooperative relationships with key stakeholders to accomplish goals</li>
      </ul>
    </div>
    <div class="honors">
      <h3>HONORS AND EDUCATION</h3>
      <ul>
        <li>Turing School of Software and Design, Denver CO</li>
        <li>President’s List, 4.0 GPA Spring ‘15 Computer Programming Colorado Mountain College</li>
        <li>Former Member of USA Cycling Under 23 National Mountain Bike Team</li>
        <li>Exercise Science/Foreign Languages, Fort Lewis College, Durango, CO</li>
      </ul>
    </div>
    <div class="experience">
      <h3>PROFESSIONAL EXPERIENCE</h3>
      <h4><strong>Marketing/Sponsorship Coordinator</strong> Honey Stinger, Carbondale/Steamboat Springs, CO 2010-2014</h4>
      <ul>
        <li>Collaboratively manages marketing activities for Honey Stinger products and promotions</li>
        <li>Optimizes marketing direction and decision-making by brainstorming and executing PR initiatives, events, and orders</li>
        <li>Builds key relationships with superior communication skills and attention to detail </li>
        <li>Adeptly handles critical event management duties, e.g. race registrations and timing</li>
        <li>Successfully creates and manages nationwide grassroots sponsorship program</li>
        <li>Skillfully manages Honey Stinger/Bontrager mountain bike race team</li>
        <li>Enhances company exposure through effective/management of social media networks, e.g. Instagram, Facebook, Twitter, YouTube, and Google+</li>
      </ul>
      <h4><strong>Marketing Coordinator</strong> Big Agnes, Carbondale/Steamboat Springs, CO 2010-2011</h4>
      <ul>
        <li>Optimizes marketing direction and decision-making by brainstorming and executing PR initiatives, events, and samples</li>
        <li>Adeptly assisted with and offered insight into product development and technical features </li>
      </ul>
    </div>
  </div>
</div>